import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import { getSession } from "@/actions/auth.action";
import { User } from "@/types/web.types";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session=await getSession();
  const user=session?.user as User|null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-900`}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
